### ISSUE TITLE
Implement Vim e (go to end of current word)

### ISSUE THREAD

**Issue by iansinnott** [thlorenz/replpad#19]
Not sure if this is an issue with my system or if it's a bug, but using `e` in Vim mode does not go to the end of the current word. `E` likewise doesn't work on my system.

Using the latest version from NPM (0.13.0 as of this writing) on OSX 10.10.2.

**Comment by thlorenz** [comment]
Please file issue with `readline-vim` repo.
Also probably a PR is welcome, I'll have no bandwidth to fix this.
Thanks.

**Comment by iansinnott** [comment]
OK
