### ISSUE TITLE
can still use deleted functions after a save

### ISSUE THREAD

**Issue by willnwhite** [thlorenz/replpad#27]
If I define a function in a file, use it in replpad, then delete the function in the file and save it, I can still use the function in replpad until I restart it. I'd expect the function to be `not defined` after the file save without having to restart.

**Comment by thlorenz** [comment]
Yeah, it's a repl, so things work differently and that won't change.
Restart the repl after you deleted the function if that bugs you.

**Comment by willnwhite** [comment]
:baby:
